In [1]:
#importing numpy 
'''
we import numpy as np because :
a) shortening it avoids the namespace issues 
b) makes your code easier to read 
'''
import numpy as np

#Note : Do not forget to import the library or importing it wrongly will raise an error that 'np' is not defined

# **Why do we use numpy ?**

Let us have a look on the significance of using Numpy. 

1. Numpy is an open source library and it can be used to perform a wide variety of mathematical operations on arrays. 
2. It adds powerful data structures to Python that guarentee efficient calculations. 
3. It also supplies an enormous library of high-level mathematical functions that operates on arrays and matrices. 

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use but NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

Now without wasting any time, lets get into the implementation part ! :)

# **1. Creating our first Numpy object** 

In [2]:
#We use 'array()' function to create the Numpy ndarray object 

arr = np.array([1,2,3,4,5])    #we have passed a list to the array() function
print("Array : ",arr)
print("Type : ",type(arr))

Array :  [1 2 3 4 5]
Type :  <class 'numpy.ndarray'>


Note : array() function takes only one parameter. It can a 'list','tuple' or can be a '2d list'

In [3]:
#passing a tuple in the array() function 

arr = np.array((1,2,3,4,5))
print("Array : ",arr)
print("Type : ",type(arr))

Array :  [1 2 3 4 5]
Type :  <class 'numpy.ndarray'>


In [4]:
#passing a 2d list to the array() function

arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Array : \n",arr)
print("Type : ",type(arr))

Array : 
 [[1 2 3 4]
 [5 6 7 8]]
Type :  <class 'numpy.ndarray'>


### **Determine the number of dimensions of the ndarray**

In [5]:
#creating ndarrays of different dimensions 

arr1 = np.array(22)
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr4 = np.array([[[1,2,3,4],[5,6,7,8]]])

#ndim : attribute provided by the numpy array 
#returning value : an integer which tells the dimensions the array have
print("Array 1 : \n",arr1)
print("Dim : ",arr1.ndim)
print()
print("Array 2 : \n",arr2)
print("Dim : ",arr2.ndim)      
print()
print("Array 3 : \n",arr3)
print("Dim : ",arr3.ndim)  
print()
print("Array 4 : \n",arr4)
print("Dim : ",arr4.ndim)  

Array 1 : 
 22
Dim :  0

Array 2 : 
 [1 2 3 4 5]
Dim :  1

Array 3 : 
 [[1 2 3 4 5]
 [1 2 3 4 5]]
Dim :  2

Array 4 : 
 [[[1 2 3 4]
  [5 6 7 8]]]
Dim :  3


In [6]:
#we can pass ndim attribute to the array() function

arr = np.array([1,2,3,4,5],ndmin=3)
print("Array : ",arr)
print("Dim : ",arr.ndim)

Array :  [[[1 2 3 4 5]]]
Dim :  3


# **2. Numpy Array Indexing & Slicing**
There is two type of indexing :
1. Positive indexing (starts from 0)
2. Negative indexing (starts from -N where N is the number of elements in the list)

### **Positive Indexing** 

In [7]:
#creating a numpy array 

arr = np.array([11,12,13,14,15])
print(arr)
print("Ele 1 : ",arr[0])
print("Ele 3 : ",arr[2])
print("Ele 1 to 3 : ",arr[0:3])   #we have performed slicing here. If you have no idea about this, do not worry we conquer this too! :) 
print("All elements : ",arr[:])
print("All elements except first 2 : ",arr[2:])

[11 12 13 14 15]
Ele 1 :  11
Ele 3 :  13
Ele 1 to 3 :  [11 12 13]
All elements :  [11 12 13 14 15]
All elements except first 2 :  [13 14 15]


In [8]:
#let's perform indexing with higher array dimension 

#2d Array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array : ",arr)
print("Dim : ",arr.ndim)
print("Ele (1,1) : ",arr[1][1])
print("Ele (0,0) : ",arr[0][0])
print("Ele (1,3) : ",arr[1][3])
print("Ele in first row : ",arr[0][:])
print("Ele in second row : ",arr[1][:])
print("All the elements in the matrix : \n",arr[:][:])

Array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dim :  2
Ele (1,1) :  7
Ele (0,0) :  1
Ele (1,3) :  9
Ele in first row :  [1 2 3 4 5]
Ele in second row :  [ 6  7  8  9 10]
All the elements in the matrix : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Negative Indexing** 

In [9]:
#let's create an array 

arr = np.array([20,21,22,23,24])
print("Array : ",arr)
print("Ele 1 : ",arr[-len(arr)])
print("Last Ele : ",arr[-1])
#if you face any confusion, do refer to the image which shows positive and negative indexing 
print("Last three element : ",arr[-3:])

Array :  [20 21 22 23 24]
Ele 1 :  20
Last Ele :  24
Last three element :  [22 23 24]


In [10]:
#negative indexing with higher dimension array 

arr = np.array([[12,14,34,26,16],[56,34,54,23,87]])
print("Array : \n",arr)
print("First row : ",arr[-len(arr)][:])
print("Ele (1,1) : ",arr[-len(arr)][-len(arr[-len(arr)])])
print("Ele (1,5) : ",arr[-len(arr)][-1])
print("Last row : ",arr[-1][:])
print("Ele (2,1) : ",arr[-1][-len(arr[-1])])
print("Ele (2,5) : ",arr[-1][-1])

Array : 
 [[12 14 34 26 16]
 [56 34 54 23 87]]
First row :  [12 14 34 26 16]
Ele (1,1) :  12
Ele (1,5) :  16
Last row :  [56 34 54 23 87]
Ele (2,1) :  56
Ele (2,5) :  87


### **Slicing in arrays**
Slicing in python simply means retrieving elements from one given index to another given index.
arr[start : end : step]

start : starting index (if no value given, then its default value is 0)<br>
end   : ending index (it is excluded, if no value mentioned then it iterates to the last element of the array)<br>
step  : step refers to the incrementing value (if no value passed, then it is 1 by default) 

In [11]:
#let's create a 2D array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr) 
print(arr[:][:])  #returns the whole matrix
print(arr[0][:])  #returns the first row
print(arr[:][0])  #returns the first row
print(arr[-1][1:3]) 
print(arr[0][-3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[1 2 3 4 5]
[7 8]
[3 4 5]


# **3. Data Types in Numpy**
Numpy has some extra data types apart from the data types python provides us. <br>
Numpy data types and the characters which represent them are : <br>
i - integer<br>
b - boolean<br>
u - unsigned integer<br>
f - float<br>
c - complex float<br>
m - timedelta<br>
M - datetime<br>
O - object<br>
S - string<br>
U - unicode string<br>
V - fixed chunk of memory for other type ( void )<br>

The Numpy array has a property 'dtype' which returns the data type of the numpy array.<br>
Let's find out the different types of data type :o

In [12]:
#data types of different arrays 
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [13]:
arr = np.array(['hello','peter'])
print(arr.dtype)

<U5


In [14]:
arr = np.array([1.1,1.2,1.3,1.4,1.5])
print(arr.dtype)

float64


In [15]:
arr = np.array([True,False,True])
print(arr.dtype)

bool


In [16]:
#What if we have different data type values in a single list ? 
#What would be the dtype of our array object then ?
#Let's dig out !!!

arr = np.array([1,'hey!',True,1.1])
print(arr.dtype)

<U21


Note : dtype is different from data type<br>

It gives us information about: <br>

a) Type of the data (integer, float, Python object, etc.)<br>
b) Size of the data (number of bytes)<br>
c) The byte order of the data (little-endian or big-endian)<br>
d) If the data type is a sub-array, what is its shape and data type?<br>

In [17]:
#Numpy allows us to create array with a defined data type 

arr = np.array([1,2,3,4,5],dtype='S')
print("Array : ",arr)
print("dtype : ",arr.dtype)

Array :  [b'1' b'2' b'3' b'4' b'5']
dtype :  |S1


In [18]:
#We can also define the size of the array with these dtypes : i, u, f, S and U

arr = np.array([1,2,3,4,5],dtype='i8')
print(arr)
print(arr.dtype)  

[1 2 3 4 5]
int64


In [19]:
#If the elements of the array cannot be converted to the defined dtype, then it raises the 'ValueError'

# arr = np.array(['hello','world'],dtype='i2')  #raises 'ValueError'
# print(arr)

In [20]:
#converting dtype of the arrays 

arr = np.array([1.1,1.2,1.3,1.4,1.5])
print(arr)
print(arr.dtype)
#converting dtype to int 
arr = arr.astype(np.int64)   #we can even specify the size of the integer with the help of numpy
print("After conversion : \n")
print(arr)
print(arr.dtype)

[1.1 1.2 1.3 1.4 1.5]
float64
After conversion : 

[1 1 1 1 1]
int64


In [21]:
arr = np.array([1, 0, 3])
print(arr)
print(arr.dtype)
arr = arr.astype(bool)
print("After conversion : ")
print(arr)
print(arr.dtype)

[1 0 3]
int64
After conversion : 
[ True False  True]
bool


# **4. Copy v/s View in Numpy**
Copy() and the view() function both creates a copy of the array. <br>
But the copy OWNS the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.<br>

While the view DOES NOT OWN the data and any changes made to the view will affect the original array

In [22]:
#copy() function 

arr = np.array(['hey','there'])

#creating a new array with copy() function 

new = arr.copy()
#let's alter our new array
new[0]='hi'
print("Newly created array : ",new)
print("Original array : ",arr)

#We can clearly see that the changes made in the newly created array were not reflected in the original array

Newly created array :  ['hi' 'there']
Original array :  ['hey' 'there']


In [23]:
#view() function 

arr = np.array(['hey','there'])

#creating a new array with view() function 

new = arr.view()
#let's alter our new array
new[0]='hi'
print("Newly created array : ",new)
print("Original array : ",arr)
#The changes made in the newly created array were reflected in the original array

Newly created array :  ['hi' 'there']
Original array :  ['hi' 'there']


# **5. Reshaping of an array in Numpy**
Firstly, let us understand what does 'shape' refers to.<br>
Shape refers to the number of elements in each dimension<br>

Numpy provides 'shape' attribute that returns a tuple with each index having number of corresponding elements. 

Note :- Do not get confuse between the shape('shape') and the dimension('ndim').

In [24]:
#getting the shape of the numpy arrays

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
#whereas ndim gives the dimension
print(arr.ndim)

(2, 5)
2


Reshaping : It means to change the shape of the array. By reshaping, we can add or remove dimensions or change the number of elements in each dimension. 

In [25]:
#converting 1D array to 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr.reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
#converting 1D array to 3D array 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = arr.reshape(2,3,2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### **Can we convert array to any shape ?**
We can convert array to any shape as long as the elements required for reshaping are equal in both shapes. <br>

We can reshape 10 elements 1D array into 5 elements in 2 rows in 2D arrays but we cannot reshape it into 5 elements in 3 rows.  

In [27]:
#what does reshape() returns ? Does it returns a copy() or a view ? 
#let's find out!

print(arr.reshape(1,12).base)

#As it returns the original array, reshape() returns like view() function

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#Flattening the array : Converting multidimensional array in single dimensional array 
'''
There are two ways to do it : 
a) using reshape() -> pass -1 to the reshape function 
b) use flatten() -> call the flatten function of the numpy array object
'''

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
#converting into 1D array 
arr = arr.reshape(-1)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
#using flatten() function 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
#converting into 1D array 
arr = arr.flatten()
print("After using flatten() function : ")
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
After using flatten() function : 
[ 1  2  3  4  5  6  7  8  9 10]


# **6. Iterating on Numpy Array**
We can ieterate through the numpy arrays in three ways :<br> 
a) Using for loop <br>
b) Using nditer() <br>
c) Using ndenumerate()

### **Using for loop**

In [30]:
#iterating 1D array
arr = np.array([1,2,3,4,5,6])

for x in arr:
    print(x)

1
2
3
4
5
6


In [31]:
#iterating 2D array 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [32]:
#iterating each element of the 2D array 
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [33]:
#iterating a 3D array 
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])

for x in arr :
    print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
#ietarting each element of the 3D array 

for x in arr :
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10


### **Using nditer()**
We have to use n loops for iterating each element of a nD array but if we use nditer() function, our task becomes easier.<br>

Let's see how!

In [35]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [36]:
#by using nditer() function we can even iterate with different step size

for x in np.nditer(arr[:, ::2]):
  print(x)

1
2
5
6


### **Using ndenumerate()**
Enumeration means mentioning sequence number of somethings one by one.<br>

In some cases we might need the index of the element too, so in those cases you can use this ndenumerate() function. 

In [37]:
arr = np.array([1, 2, 3, 4, 5])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


# **7. Joining Numpy Arrays**
There are two ways to join the numpy arrays :<br> 
a) Using concatenate() function<br>
b) Using stack() functions

### **Using concatenate()**

In [38]:
#joining two 1D arrays 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [39]:
#If we change the argument 'axis' to 1 in the concatenate function, then the arrays will be concatenated row wise 
arr1 = np.array([[1],[ 2],[ 3]])
arr2 = np.array([[4], [5], [6]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
#joining two 2D arrays 
arr1 = np.array([[1, 2, 3],[7,8,9]])
arr2 = np.array([[4, 5, 6],[10,11,12]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [41]:
#joining two arrays with different dimensions 
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],[7,8,9],[10,11,12]])
# arr = np.concatenate((arr1, arr2))   #contenate function cannot join two arrays with different dimension
#we can use column_stack function for completing this task
arr = np.column_stack((arr1,arr2))
print(arr)

[[ 1  4  5  6]
 [ 2  7  8  9]
 [ 3 10 11 12]]


### **Using stack() function**

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [43]:
#when axis = 1 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


There are three more stack functions : <br>
a) hstack() : It stacks along rows<br>
b) vstack() : It stacks along columns<br>
c) dstack() : It stacks along height (depth)

In [44]:
#hstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [45]:
#vstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [46]:
#dstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# **8. Splitting Numpy Arrays**
Splitting : breaking an array into multiple arrays.<br>
We use the array_split() function. 
<br>It takes two arguments : <br>
a) the array which has to be split<br>
b) the number of splits

In [47]:
#Splitting 1D array into 3
arr = np.array([1,2,3,4,5,6])
arr = np.array_split(arr,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
#Splittig 2d array 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr = np.array_split(arr,3)
print(arr)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int64)]


In [49]:
#Splitting along rows
#For achieveing this, set axis=1 in array_split() function
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr = np.array_split(arr,3,axis=1)
print(arr)

[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]]), array([[ 5],
       [10]])]


# **9. Searching elements in Numpy Arrays**
There are two ways to perform serach operation in numpy arrays : <br>
a) Using where() func.<br>
b) Using searchsorted() func.

### **Using where()**

In [50]:
#where() function returns all the index values where the element is found
arr = np.array([11,12,13,14,12,12,15,16])
x = np.where(arr == 12)
print(x)

(array([1, 4, 5]),)


In [51]:
#what if element is not found ? 
arr = np.array([11,12,13,14,12,12,15,16])
x = np.where(arr == 100)
print(x)

#an empty list is returned when the element is not found

(array([], dtype=int64),)


### **Using searchsorted()**
searchsorted() : It performs binary search in the array, and returns the index where the element is found. <br>
Note : searchsorted() works on sorted arrays

In [52]:
arr = np.array([6, 7, 7, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [53]:
#if we want to search element from the right side, then we can set the side='right' inside the searchsorted() function
arr = np.array([6, 7, 7, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

4


# **10. Sorting in Numpy Arrays**
Sorting means putting elements in an ordered sequence.<br>
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

Numpy array has a function sort() which sorts the specified array. 

In [54]:
#Sorting a 1D array : It sorts all the sub arrays
arr = np.array([4,3,2,5,6,1,8])
print(arr)
print("Array after sorting : ")
arr = np.sort(arr)
print(arr)

[4 3 2 5 6 1 8]
Array after sorting : 
[1 2 3 4 5 6 8]


In [55]:
#sorting a 2D array 
arr = np.array([[4,3,2,1],[6,5,4,3]])
print(arr)
print("Array after sorting : ")
arr = np.sort(arr)
print(arr)


[[4 3 2 1]
 [6 5 4 3]]
Array after sorting : 
[[1 2 3 4]
 [3 4 5 6]]


In [56]:
#sorting in descending order : set axis=0 
arr = np.array([[4,3,2,1],[6,5,4,3]])
print(arr)
print("Array after sorting : ")
arr = np.sort(arr,axis=0)
print(arr)

[[4 3 2 1]
 [6 5 4 3]]
Array after sorting : 
[[4 3 2 1]
 [6 5 4 3]]
