# **Lab Experiment 1**

### **Installation Of PyTorch**

Visit the PyTorch's official website : https://pytorch.org

Select the specifications according to the specification of your system and copy the command provided in the "Run this command" box. Copy & paste it in the terminal and install pytorch in your system

![](2022-08-29-13-40-41.png)

![](2022-08-29-13-43-58.png)

After few minutes, the PyTorch will be installed in your system and you are good to go for the exploration of Pytorch.

### **Basics of Torch & Tensor Creation**

In [1]:
# importing the required libraries
import torch
import pandas as pd
import numpy as np

In [2]:
# creating a list 
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [3]:
# we can create a tensor using numpy array with the help of from_numpy() function.
nlist = np.array(l)
nlist 

array([1, 2, 3, 4, 5])

In [4]:
# dtype of the nlist
nlist.dtype

dtype('int32')

In [5]:
# now converting the nlist into tensor using from_numpy() function
tlist = torch.from_numpy(nlist)
tlist

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
# point to note is that the numpy array and the tensor we have created from it shares the same memory location
# we can confirm it by allocation a value to an index of the tensor
tlist[2] = 100
tlist

tensor([  1,   2, 100,   4,   5], dtype=torch.int32)

In [7]:
# printing the numpy array
nlist
# we can see that the changes made to tensor are beng reflected here. This can be a drawback of the from_numpy() function

array([  1,   2, 100,   4,   5])

Another way to create a tensor is by using the tensor() function. It overcomes the drawback of the from_numpy() function because it returns the copy of the passed list or numpy array

In [8]:
# creating a tensor from the list
# tensor() creates a copy from the list. (They do not share the same memory)
# also knowns as leaf tensor
t = torch.tensor(l,dtype=torch.float)
t

tensor([1., 2., 3., 4., 5.])

In [9]:
# torch uses float 32 as the default type 
torch.get_default_dtype()

torch.float32

### **Tensor Manipulations**

In [10]:
# zeros() -> returns a tensor filled the scalar zeros of the shape passed as an argument
torch.zeros(3,2,dtype=torch.float)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
# ones -> returns a tensor filled with 1s of the shape passed as an argument to the function
torch.ones(4,5,dtype=torch.float32)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [12]:
# arange() -> returns a 1-D tensor from the beginning to end-1 numbers 
torch.arange(0,15)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# we can also provide the step size (the value with which the value of the numbers increase)
torch.arange(0,15,2)
# 2 is the step value which I have provided to the function

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [14]:
# we can also change the dimension of the 1-d tensor we have created above
temp = torch.arange(0,16,2)
print("Size : ",temp.shape)
print("Dimension : ",temp.dim())

Size :  torch.Size([8])
Dimension :  1


In [15]:
# reshape() -> using the reshape function to change the dimension of the tensor we have created using the arange() function
torch.reshape(temp,(2,4))

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]])

In [16]:
# eye() : returns a tensor with 1s on the diagonal places and 0s elsewhere
# using the out parameter to decide where to store the output of this function
torch.eye(5,5,out=temp)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [17]:
# tensor returned from the eye() function is being stored in the temp 
temp

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [18]:
# empty() : returns a tensor with the unitialised data
torch.empty(5,3)

tensor([[7.3470e-39, 8.9082e-39, 9.5510e-39],
        [1.0469e-38, 6.7959e-39, 9.1837e-39],
        [1.0745e-38, 8.4490e-39, 9.6428e-39],
        [1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39]])

In [19]:
# full() -> it takes size and the fill number as the input and returns the tensor of the provided size and fills with the fill number
torch.full((4,3),3)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

In [20]:
# creating a tensor
l = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
temp = torch.tensor(l)
temp

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [21]:
# squeeze() -> returns a tensor with all the dimensions of input of size 1 removed
torch.squeeze(temp,0)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [22]:
# finding the transpose of the matrix
# it takes two input parameters : dim0 and dim1
# what it does it swaps the dim0 with the dim1
temp.transpose(0,1)

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [23]:
# creating two 1d tensors 
l1 = torch.tensor([1,2,3,4],dtype=torch.float)
l1

tensor([1., 2., 3., 4.])

In [24]:
l2 = torch.tensor([5,6,7,8],dtype=torch.float)
l2

tensor([5., 6., 7., 8.])

In [25]:
# dot product of two tensors
torch.dot(l1,l2)

tensor(70.)

In [26]:
# now creating 2d matrices to perform more operations
m1 = torch.tensor([[1,2,3,4],
                    [5,6,7,8]],dtype=torch.float)
m1

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [27]:
# another matrix
m2 = torch.tensor([[8,7,6,5],
                    [4,3,2,1]],dtype=torch.float)
m2

tensor([[8., 7., 6., 5.],
        [4., 3., 2., 1.]])

In [28]:
# dot product of two matrices
# performing the dot product of the two passed matrices
torch.mm(m1,m2.transpose(0,1))

tensor([[ 60.,  20.],
        [164.,  60.]])

In [29]:
# matrix multiplication
torch.multiply(m1,m2)

tensor([[ 8., 14., 18., 20.],
        [20., 18., 14.,  8.]])

In [30]:
# adding two matrices using the add() function
torch.add(m1,m2)

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.]])

In [31]:
# subtracting two matrices using the sub() function
torch.sub(m1,m2)

tensor([[-7., -5., -3., -1.],
        [ 1.,  3.,  5.,  7.]])

In [32]:
# finding the sum of the matrix 
m1.sum()

tensor(36.)

In [33]:
# if we wish to find the sigmoid of a value we can 
# compute it by using the sigmoid function
torch.sigmoid(m2.sum())

tensor(1.)

In [34]:
# lets verify the sigmoid value returned by the sigmoid function by creating our own sigmoid function
def sig(val):
    return (1/(1+np.exp(-1*val)))

In [35]:
sig(m2.sum())

tensor(1.)

In [36]:
# finding the hyperbolic tangent value using the tanh() function 
torch.tanh(m2)

tensor([[1.0000, 1.0000, 1.0000, 0.9999],
        [0.9993, 0.9951, 0.9640, 0.7616]])

In [37]:
# understanding the relu() function which is also an activation function used in the nn
m2 = torch.tensor([-1,4,-3,66,-90,123,-2.12],dtype=torch.float)
# relu(x) -> max(0,x)
torch.relu(m2)

tensor([  0.,   4.,   0.,  66.,   0., 123.,   0.])

In [38]:
# generating a tensor filled with the random values
# rand() function returns a tensor filled with random generated values in the range 0-1 and of size passed to it.
torch.rand((2,3))

tensor([[0.1991, 0.4510, 0.9512],
        [0.5893, 0.4750, 0.9424]])

In [39]:
# randn() : values returned by this function have mean 0 and variance 1 (also called the standard normal distribution)
torch.randn((2,4))

tensor([[-0.4448, -1.4837,  0.5613, -0.9914],
        [ 0.8532,  0.9323, -0.9499,  0.4595]])

In [40]:
# printing  the matrix m2
m2

tensor([ -1.0000,   4.0000,  -3.0000,  66.0000, -90.0000, 123.0000,  -2.1200])

In [41]:
# finding the absolute values 
torch.abs(m2)

tensor([  1.0000,   4.0000,   3.0000,  66.0000,  90.0000, 123.0000,   2.1200])

In [42]:
# it applies the negation to all the values of the tensor matrix
torch.neg(m2)

tensor([   1.0000,   -4.0000,    3.0000,  -66.0000,   90.0000, -123.0000,
           2.1200])

In [43]:
# reciprocal() : returns a tensor with the reciprocal of all the values present in the tensor
temp = torch.reciprocal(m2)
temp

tensor([-1.0000,  0.2500, -0.3333,  0.0152, -0.0111,  0.0081, -0.4717])

In [44]:
# round() -> rounds elements of input to their nearest integer 
temp.round()

tensor([-1.,  0., -0.,  0., -0.,  0., -0.])

In [45]:
# printing the matrix m1
m1

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [46]:
# finding the square root of the elements of the matrix
torch.sqrt(m1)

tensor([[1.0000, 1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458, 2.8284]])

In [47]:
# finding the square of the elements of matrix
torch.square(m1)

tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 64.]])

In [48]:
# creating a tensor with random values 
temp = torch.rand((3,4))
temp

tensor([[0.6949, 0.2642, 0.3502, 0.2938],
        [0.6073, 0.5340, 0.9635, 0.1277],
        [0.2322, 0.2170, 0.3526, 0.7582]])

In [49]:
# argmax() function : returns the indices of the maximum value in the specified row
torch.argmax(temp,dim=1)

tensor([0, 2, 3])

In [50]:
# argmin() : returns the indices of the minimum values in the specified row
torch.argmin(temp,dim=1)

tensor([1, 3, 1])

In [51]:
# max() : finding the maximum value of the input tensor
temp.max()

tensor(0.9635)

In [52]:
# finding the minimum value of the input tensor
temp.min()

tensor(0.1277)

In [53]:
# finding the mean of the input tensor
temp.mean()

tensor(0.4496)

In [54]:
# finding the median of the input tensor
temp.median()

tensor(0.3502)

In [55]:
# finding the standard deviation of the each row present in the input tensor
temp.std(1)

tensor([0.1993, 0.3428, 0.2529])

In [56]:
# computing the covariance of the input tensor
temp.cov()

tensor([[ 0.0397,  0.0144, -0.0201],
        [ 0.0144,  0.1175, -0.0591],
        [-0.0201, -0.0591,  0.0639]])

In [57]:
temp = torch.tensor([1,2,3,4,5,6,7,8])
temp.diag()

tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0, 0],
        [0, 0, 0, 4, 0, 0, 0, 0],
        [0, 0, 0, 0, 5, 0, 0, 0],
        [0, 0, 0, 0, 0, 6, 0, 0],
        [0, 0, 0, 0, 0, 0, 7, 0],
        [0, 0, 0, 0, 0, 0, 0, 8]])

In [58]:
temp = temp.diagflat()
temp.flatten()

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
        0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0,
        0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 8])

In [59]:
m1 = torch.rand((4,4))
m1

tensor([[0.0091, 0.4694, 0.9919, 0.5365],
        [0.9777, 0.7274, 0.6367, 0.9341],
        [0.5569, 0.7015, 0.0193, 0.8369],
        [0.4092, 0.4457, 0.5785, 0.1746]])

In [60]:
# finding the inverse of the matrix
m1.inverse()

tensor([[-1.1077,  1.4452, -0.9741,  0.3410],
        [-0.1249, -2.4960,  2.2637,  2.8862],
        [ 0.6300,  0.5634, -1.0458,  0.0632],
        [ 0.8272,  1.1176, -0.0303, -2.6476]])